image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - target/kotlin-ic
    - target/classes
    - target/test-classes
    - target/maven-archiver

stages:
  - package

package_6502emulator:
  stage: package
  script:
    - mvn clean package
  artifacts:
    paths:
      - Emulator/target/*-with-dependencies.jar
  tags:
    - docker
