image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - Emulator/target/kotlin-ic
    - Emulator/target/classes
    - Emulator/target/test-classes
    - Emulator/target/maven-archiver
    - Lib6502/target/kotlin-ic
    - Lib6502/target/classes
    - Lib6502/target/test-classes
    - Lib6502/target/maven-archiver
    - KotlinUtils/target/kotlin-ic
    - KotlinUtils/target/classes
    - KotlinUtils/target/test-classes
    - KotlinUtils/target/maven-archiver

stages:
  - package

package_6502emulator:
  stage: package
  script:
    - mvn clean package
  artifacts:
    paths:
      - Emulator/target/*-with-dependencies.jar
  tags:
    - docker
